name: "Set up Gradle Action"
inputs:
  cache-read-only:
    required: true
    description: Cache read-only state

  gradle-encryption-key:
    required: true
    description: Gradle Cache encryption key

runs:
  using: "composite"
  steps:
    - name: Generate Wrapper
      run: gradlew wrapper
      shell: bash

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Cache data needs to be encrypted to be safely stored in the GitHub Actions cache
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}

        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ inputs.cache-read-only }}