name: "Set up Gradle Action"
runs:
  using: "composite"
  steps:
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
