name: "Set up Keystore Action"
runs:
  using: "composite"
  steps:
    - name: âš™ï¸ Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks
      shell: bash

    - name: ðŸ”‘ Create keystore.properties
      run: |
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
      shell: bash
