name: "Set up Keystore Action"

inputs:
  file:
    required: true
    description: "A keystore file name"

  keystore:
    required: true
    description: "A Base64-encoded keystore"

  keystorePassword:
    required: true
    description: "A keystore password"

  keyAlias:
    required: true
    description: "A key alias to use"

  keyPassword:
    required: true
    description: "A key password"

runs:
  using: "composite"
  steps:
    - name: ⚙️ Decode Keystore
      run: |
        echo "${{ inputs.keystore }}" | base64 -d > app/${{ inputs.file }}
      shell: bash

    - name: 🔑 Create keystore.properties
      run: |
          cat <<EOF > keystore.properties
          storeFile=${{ inputs.file }}
          storePassword=${{ inputs.keystorePassword }}
          keyAlias=${{ inputs.keyAlias }}
          keyPassword=${{ inputs.keyPassword }}
          EOF
      shell: bash
